export const listData = [
  {
    id: 1,
    title: "Modern Apartment in KLCC",
    images: ["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 2,
    bathroom: 1,
    price: 2500,
    address: "Jalan Ampang, Kuala Lumpur",
    latitude: 3.1319,
    longitude: 101.6841,
    city: "Kuala Lumpur",
    type: "rent",
    property: "apartment"
  },
  {
    id: 2,
    title: "Luxury Condo in Mont Kiara",
    images: ["https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 3,
    bathroom: 2,
    price: 3500,
    address: "Jalan Kiara, Mont Kiara, Kuala Lumpur",
    latitude: 3.1728,
    longitude: 101.6508,
    city: "Kuala Lumpur",
    type: "rent",
    property: "condo"
  },
  {
    id: 3,
    title: "Affordable Studio in Petaling Jaya",
    images: ["https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 1,
    bathroom: 1,
    price: 1200,
    address: "Jalan SS2, Petaling Jaya",
    latitude: 3.1146,
    longitude: 101.6195,
    city: "Petaling Jaya",
    type: "rent",
    property: "apartment"
  },
  {
    id: 4,
    title: "Beautiful House in Subang Jaya",
    images: ["https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 4,
    bathroom: 3,
    price: 850000,
    address: "USJ Heights, Subang Jaya",
    latitude: 3.0437,
    longitude: 101.5851,
    city: "Subang Jaya",
    type: "buy",
    property: "house"
  },
  {
    id: 5,
    title: "Penthouse in Bangsar",
    images: ["https://images.pexels.com/photos/276625/pexels-photo-276625.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 3,
    bathroom: 2,
    price: 4500,
    address: "Bangsar South, Kuala Lumpur",
    latitude: 3.1193,
    longitude: 101.6670,
    city: "Kuala Lumpur",
    type: "rent",
    property: "condo"
  },
  {
    id: 6,
    title: "Cozy Apartment in Shah Alam",
    images: ["https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 2,
    bathroom: 1,
    price: 1500,
    address: "Section 7, Shah Alam",
    latitude: 3.0733,
    longitude: 101.5185,
    city: "Shah Alam",
    type: "rent",
    property: "apartment"
  },
  {
    id: 7,
    title: "Family House in Kajang",
    images: ["https://images.pexels.com/photos/2029667/pexels-photo-2029667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 3,
    bathroom: 2,
    price: 650000,
    address: "Taman Kajang Utama, Kajang",
    latitude: 2.9923,
    longitude: 101.7890,
    city: "Kajang",
    type: "buy",
    property: "house"
  },
  {
    id: 8,
    title: "Modern Condo in Cyberjaya",
    images: ["https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
    bedroom: 2,
    bathroom: 2,
    price: 2200,
    address: "Persiaran APEC, Cyberjaya",
    latitude: 2.9213,
    longitude: 101.6559,
    city: "Cyberjaya",
    type: "rent",
    property: "condo"
  },
];

export const singlePostData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 1200,
  images: [
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: 51.5074,
  longitude: -0.1278,
  city: "London",
  address: "1234 Broadway St",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
};

export const userData = {
  id: 1,
  name: "John Doe",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};